### ISSUE TITLE
Creating the secret key fails

### ISSUE THREAD

**Issue by wilhelmy** [Metalab/mos#68]
Following the instructions from the `HACKING` file, I managed to get to step 7, which gave the following output:

```
(devel) fukushima ~/s/mos & python manage.py generate_secret_key
Traceback (most recent call last):
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django/core/management/__init__.py", line 179, in fetch_command
    app_name = commands[subcommand]
KeyError: 'generate_secret_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mw/src/mos/mos/settings/common.py", line 9, in <module>
    from .secret_key import *
ImportError: No module named 'mos.settings.secret_key'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django/core/management/__init__.py", line 182, in fetch_command
    settings.INSTALLED_APPS
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/mw/src/mos/devel/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/mw/src/mos/mos/settings/devel.py", line 2, in <module>
    from .common import *
  File "/home/mw/src/mos/mos/settings/common.py", line 12, in <module>
    from django_extensions.management.commands import generate_secret_key
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django_extensions/management/commands/generate_secret_key.py", line 5, in <module>
    from django_extensions.compat import CompatibilityBaseCommand as BaseCommand
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django_extensions/compat.py", line 33, in <module>
    from django.contrib.auth import get_user_model
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 7, in <module>
    from django.middleware.csrf import rotate_token
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django/middleware/csrf.py", line 14, in <module>
    from django.utils.cache import patch_vary_headers
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django/utils/cache.py", line 26, in <module>
    from django.core.cache import caches
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django/core/cache/__init__.py", line 34, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/mw/src/mos/devel/lib/python3.5/site-packages/django/conf/__init__.py", line 113, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

Any ideas how to solve this?

**Comment by norpol** [comment]
I can reproduce this error with Python 2.7.12.
Without further modifications, you won't be able to use Python 3.

**Comment by wilhelmy** [comment]
Oh oops, I'll use python2.7 then ­— if the error also occurs on python 2.7, this is still a bug though.

**Comment by wilhelmy** [comment]
I'm going to update the instructions so that it works
